mysite/contacts/urls.py
from django.urls import path
from contacts.views import contact_page


app_name = "contacts"

urlpatterns = [

    path("", contact_page, name="get-contacts-page"),
]

mysite/gallery/urls.py
from django.urls import path
from gallery.views import gallery


app_name = "gallery"


urlpatterns = [

    path("", gallery, name="get-gallery-page"),
    


]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mysite.views import index



urlpatterns = (
    [
        path("staff/", admin.site.urls),
        path("services/", include("services.urls", namespace="services")),
        path("contacts/", include("contacts.urls", namespace = "contacts")),
        path("gallery/", include("gallery.urls", namespace= "gallery") ),
        path("",  index),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

mysite/services/urls.py
from django.urls import path
from services.views import get_services, get_service


app_name = "services"

urlpatterns = [

    path("", get_services, name="get-services-page"),
    path("<id>/", get_service, name="get-service"),


]

mysite/contacts/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    email = models.EmailField(max_length=150)
    message = models.TextField()

class ContactBackgrounds(models.Model):
    image = models.ImageField(
        upload_to="posts/bg/",
    )

mysite/gallery/models.py
from django.db import models

class HomePicture(models.Model):
    image = models.ImageField(
        upload_to="posts/bg/",
    )

class WelcomePicture(models.Model):
    image = models.ImageField(
        upload_to="posts/bg/",
    )

class GalleryBackground(models.Model):
    image = models.ImageField(
        upload_to="posts/bg/",
    )

class GalleryImages(models.Model):
    image1 = models.ImageField(
    upload_to="posts/bg/",
    )
    image2 = models.ImageField(
    upload_to="posts/bg/",
    )
    image3 = models.ImageField(
    upload_to="posts/bg/",
    )
    image4 = models.ImageField(
    upload_to="posts/bg/",
    )
    image5 = models.ImageField(
    upload_to="posts/bg/",
    )
    image6 = models.ImageField(
    upload_to="posts/bg/",
    )
    image7 = models.ImageField(
    upload_to="posts/bg/",
    )
    image8 = models.ImageField(
    upload_to="posts/bg/",
    )
    image9 = models.ImageField(
    upload_to="posts/bg/",
    )

mysite/mysite/models.py
from django.db import models


class HeadPicture(models.Model):
    image = models.ImageField(
        upload_to="posts/bg/",
    )

mysite/services/models.py
from django.db import models

# Create your models here.
class Service(models.Model):
    name = models.CharField(blank=False, null=False, max_length=10000)
    description = models.TextField(blank=False, null=False)
    image = models.ImageField(blank=False, null=False)

class ContactImages(models.Model):
    image1 = models.ImageField(
        upload_to="posts/bg/",
    )
    image2 = models.ImageField(
        upload_to="posts/bg/",
    )
    image3 = models.ImageField(
        upload_to="posts/bg/",
    )

class ServicesBackground(models.Model):
    image = models.ImageField(
        upload_to="posts/bg/",
    )
    
    

mysite/contacts/forms.py
from django import forms
from contacts.models import Contact

class ContactForm(forms.ModelForm):
    name = forms.CharField(required=True,widget=forms.TextInput(
        attrs = {
            "class": "w-full bg-gray-300 text-red-500 font-black border-4 rounded border-black ",
            "placeholder": "Please enter your name"
        }
    ))

    surname = forms.CharField(required=True,widget=forms.TextInput(
        attrs = {
            "class": "w-full bg-gray-300 border-4 rounded border-black ",
            "placeholder": "Please enter your surname"
        }
    ))

    email = forms.CharField(required=True,widget=forms.TextInput(
        attrs = {
            "class": "w-full bg-gray-300 border-4 rounded border-black ",
            "placeholder": "Please enter your email"
        }
    ))

    message = forms.CharField(required=True,widget=forms.TextInput(
        attrs = {
            "class": "w-full h-20 bg-gray-300 border-4 rounded border-black ",
            "placeholder": "Please enter your message"
        }
    ))


    class Meta:
        model = Contact
        fields = (
            "name",
            "surname",
            "email",
            "message",
        )

mysite/contacts/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse




# Create your views here.
def contact_page(request):
    if request.method == "POST":
        form = ContactForm(request.POST)  
        if form.is_valid():
            subject = "Website Inquiry"
            form.save() 

            try:
                send_mail(subject, "message", "admin@example.com", ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse("Invalid header found.")
            return redirect("contacts:get-contacts-page")


    
    
    

    form = ContactForm()

    context = {
        "form":form,
        
        
    }
    return render(request, "public/contacts/contacts.html", context)

mysite/gallery/views.py
from django.shortcuts import render

from gallery.models import GalleryImages, GalleryBackground


# Create your views here.
def gallery(request):
    image = GalleryImages.objects.all()
    bg = GalleryBackground.objects.last()
    context = {
        "image" : image,
        "bg" : bg,

    }
    
    return render(request, "public/gallery/gallery.html", context)

    
    

mysite/mysite/views.py
from gallery.models import  HomePicture, WelcomePicture
from django.shortcuts import render 

def index(request):
    bg = HomePicture.objects.last()
    welcome_pic = WelcomePicture.objects.last()
    context = {
        "bg": bg,
        "wp" : welcome_pic,
    }
    return render(request, "public/index.html", context)

mysite/services/views.py
from django.http import Http404
from django.shortcuts import render
from services.models import Service
from services.models import ContactImages, ServicesBackground


# Create your views here.
def get_services(request):
    image = ContactImages.objects.last()
    bg = ServicesBackground.objects.last()
    done = {
        "images": image,
        "bg" : bg,
    }
    return render(request, "public/services/services.html", done)


def get_service(request, id):
    try:
        services = Service.objects.get(id=id)

    except:
        raise Http404("Service not found")

    context = {"request": request, "services": services}

    return render(request, "public/services/get-services.html", context)

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css" integrity="sha512-wnea99uKIC3TJF7v4eKk4Y+lMz2Mklv18+r4na2Gn1abDRPPOeef95xTzdwGD9e6zXJBteMIhZ1+68QC5byJZw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Spline+Sans+Mono:wght@500&display=swap" rel="stylesheet">
    {% block styles %}{% endblock %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <style>
        * {
            font-family: 'Spline Sans Mono', monospace;
        }
    </style>
</head>
<body >
    
    {% include 'components/navbar.html' %}
    {% block body %}{% endblock %}
    {% include 'components/footer.html' %}
</div>
</body>
</html>

mysite/templates/components/footer.html
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
{% load static %}    
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<footer>
    <p class="logo">Driving <span>Masters</span></p>
    <p class="logo"><span>Email: </span> info@drivingmasters.co.za
    <br>
    <span>Tel: </span> 0722779590
    <br>
    <span>Tel: </span> 0833072491
    <br>
    <span>Address: </span> Rietvlei Farm, 101 Swartkoppies Road, Alberton, 1448
    </p>

    <p class="end"> CopyRight by Driving Masters</p>
  
  
  </footer>

    </body>
   

mysite/templates/components/navbar.html
{% block style %}
<style>
   /* Create a top navigation bar with a black background color  */
.topnav {
  background-color: #333;
  overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

/* Change the color of links on hover */
.topnav a:hover {
  background-color: #ddd;
  color: black;
}

/* Create a right-aligned (split) link inside the navigation bar */
.topnav a.split {
  float: right;
  background-color: #04AA6D;
  color: white;
}
</style>
{% endblock %}


<div class="topnav">
  <a href="/"><i class="fa fa-fw fa-home"></i> Home</a>
  <a href="{% url 'services:get-services-page' %}"><i class="fa fa-fw fa-wrench"></i> Services</a>
  <a href="{% url 'contacts:get-contacts-page' %}"><i class="fa fa-fw fa-envelope"></i> Contacts</a>
  <a href="{% url 'gallery:get-gallery-page' %}"><i class="fa fa-fw fa-envelope"></i> Gallery</a>
</div> 